name: Deploy Website
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ vars.DOMAIN }}
    steps:
      - uses: actions/checkout@v6
      - name: Deploy on Home Server
        uses: Burnett01/rsync-deployments@8.0.5
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /srv/www/${{ vars.DOMAIN }}/main
          remote_host: ${{ vars.DOMAIN }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          remote_port: ${{ vars.SERVER_SSH_PORT }}
